import type { Vehicle, Driver, Student, Stop, Route, Incident, DashboardKPI } from "./types"

// Mock vehicles
export const mockVehicles: Vehicle[] = [
  {
    id: "v1",
    plateNumber: "29A-12345",
    capacity: 45,
    gpsDeviceId: "GPS001",
    imei: "123456789012345",
    status: "active",
    inspectionExpiry: "2025-12-31",
    insuranceExpiry: "2025-11-30",
    fuelLevel: 75,
    currentLocation: {
      lat: 21.0285,
      lng: 105.8542,
      speed: 35,
      heading: 90,
      timestamp: new Date().toISOString(),
    },
  },
  {
    id: "v2",
    plateNumber: "30B-67890",
    capacity: 35,
    gpsDeviceId: "GPS002",
    imei: "123456789012346",
    status: "active",
    inspectionExpiry: "2025-10-15",
    insuranceExpiry: "2025-09-20",
    fuelLevel: 60,
    currentLocation: {
      lat: 21.0245,
      lng: 105.8412,
      speed: 25,
      heading: 180,
      timestamp: new Date().toISOString(),
    },
  },
  {
    id: "v3",
    plateNumber: "29C-11111",
    capacity: 50,
    gpsDeviceId: "GPS003",
    imei: "123456789012347",
    status: "maintenance",
    inspectionExpiry: "2026-01-20",
    insuranceExpiry: "2025-12-15",
    lastMaintenance: "2025-01-05",
    nextMaintenance: "2025-04-05",
  },
  {
    id: "v4",
    plateNumber: "30D-22222",
    capacity: 40,
    gpsDeviceId: "GPS004",
    imei: "123456789012348",
    status: "active",
    inspectionExpiry: "2025-11-10",
    insuranceExpiry: "2025-10-25",
    fuelLevel: 85,
    currentLocation: {
      lat: 21.0195,
      lng: 105.8352,
      speed: 40,
      heading: 270,
      timestamp: new Date().toISOString(),
    },
  },
]

// Mock drivers
export const mockDrivers: Driver[] = [
  {
    id: "d1",
    name: "Nguyễn Văn An",
    licenseNumber: "B2-123456",
    licenseClass: "D",
    licenseExpiry: "2027-06-15",
    phone: "0912345678",
    email: "nva@ssb.vn",
    status: "active",
    trustScore: 95,
    emergencyContact: {
      name: "Nguyễn Thị Bình",
      phone: "0987654321",
      relationship: "Vợ",
    },
    violations: 0,
  },
  {
    id: "d2",
    name: "Trần Minh Tuấn",
    licenseNumber: "B2-234567",
    licenseClass: "D",
    licenseExpiry: "2026-03-20",
    phone: "0923456789",
    email: "tmt@ssb.vn",
    status: "active",
    trustScore: 88,
    emergencyContact: {
      name: "Trần Thị Lan",
      phone: "0976543210",
      relationship: "Vợ",
    },
    violations: 1,
  },
  {
    id: "d3",
    name: "Lê Hoàng Nam",
    licenseNumber: "B2-345678",
    licenseClass: "D",
    licenseExpiry: "2025-09-10",
    phone: "0934567890",
    email: "lhn@ssb.vn",
    status: "on-leave",
    trustScore: 92,
    emergencyContact: {
      name: "Lê Thị Mai",
      phone: "0965432109",
      relationship: "Vợ",
    },
    violations: 0,
  },
  {
    id: "d4",
    name: "Phạm Đức Hải",
    licenseNumber: "B2-456789",
    licenseClass: "D",
    licenseExpiry: "2028-01-25",
    phone: "0945678901",
    email: "pdh@ssb.vn",
    status: "active",
    trustScore: 97,
    emergencyContact: {
      name: "Phạm Thị Hoa",
      phone: "0954321098",
      relationship: "Vợ",
    },
    violations: 0,
  },
]

// Mock stops
export const mockStops: Stop[] = [
  {
    id: "s1",
    name: "Cổng trường THCS Chu Văn An",
    lat: 21.0285,
    lng: 105.8542,
    geofenceRadius: 50,
    capacity: 30,
    studentIds: ["st1", "st2", "st3"],
    address: "187 Tây Sơn, Đống Đa, Hà Nội",
  },
  {
    id: "s2",
    name: "Ngã tư Ô Chợ Dừa",
    lat: 21.0245,
    lng: 105.8412,
    geofenceRadius: 40,
    capacity: 25,
    studentIds: ["st4", "st5"],
    address: "Ngã tư Ô Chọ Dừa, Đống Đa, Hà Nội",
  },
  {
    id: "s3",
    name: "Công viên Thống Nhất",
    lat: 21.0195,
    lng: 105.8352,
    geofenceRadius: 45,
    capacity: 20,
    studentIds: ["st6", "st7"],
    address: "Công viên Thống Nhất, Hai Bà Trưng, Hà Nội",
  },
  {
    id: "s4",
    name: "Bến xe Giáp Bát",
    lat: 21.0015,
    lng: 105.8312,
    geofenceRadius: 60,
    capacity: 35,
    studentIds: ["st8", "st9", "st10"],
    address: "Giải Phóng, Hoàng Mai, Hà Nội",
  },
]

// Mock routes
export const mockRoutes: Route[] = [
  {
    id: "r1",
    name: "Tuyến 01 - Đống Đa",
    code: "DD-01",
    shiftType: "morning",
    status: "in-progress",
    stops: [
      { stopId: "s1", sequence: 1, estimatedTime: "07:00", bufferMinutes: 5 },
      { stopId: "s2", sequence: 2, estimatedTime: "07:15", bufferMinutes: 5 },
      { stopId: "s3", sequence: 3, estimatedTime: "07:30", bufferMinutes: 5 },
    ],
    estimatedDuration: 45,
    distance: 12.5,
    version: 1,
    isActive: true,
  },
  {
    id: "r2",
    name: "Tuyến 02 - Hoàng Mai",
    code: "HM-02",
    shiftType: "morning",
    status: "scheduled",
    stops: [
      { stopId: "s4", sequence: 1, estimatedTime: "06:45", bufferMinutes: 5 },
      { stopId: "s3", sequence: 2, estimatedTime: "07:00", bufferMinutes: 5 },
      { stopId: "s1", sequence: 3, estimatedTime: "07:20", bufferMinutes: 5 },
    ],
    estimatedDuration: 50,
    distance: 15.2,
    version: 1,
    isActive: true,
  },
  {
    id: "r3",
    name: "Tuyến 01 - Đống Đa (Chiều)",
    code: "DD-01-PM",
    shiftType: "afternoon",
    status: "scheduled",
    stops: [
      { stopId: "s3", sequence: 1, estimatedTime: "16:00", bufferMinutes: 5 },
      { stopId: "s2", sequence: 2, estimatedTime: "16:15", bufferMinutes: 5 },
      { stopId: "s1", sequence: 3, estimatedTime: "16:30", bufferMinutes: 5 },
    ],
    estimatedDuration: 45,
    distance: 12.5,
    version: 1,
    isActive: true,
  },
]

// Mock students
export const mockStudents: Student[] = [
  {
    id: "st1",
    code: "HS001",
    name: "Nguyễn Minh Anh",
    grade: "6A",
    school: "THCS Chu Văn An",
    defaultPickupStopId: "s1",
    defaultDropoffStopId: "s1",
    defaultRouteId: "r1",
  },
  {
    id: "st2",
    code: "HS002",
    name: "Trần Bảo Ngọc",
    grade: "7B",
    school: "THCS Chu Văn An",
    defaultPickupStopId: "s1",
    defaultDropoffStopId: "s1",
    defaultRouteId: "r1",
  },
  {
    id: "st3",
    code: "HS003",
    name: "Lê Hoàng Long",
    grade: "8C",
    school: "THCS Chu Văn An",
    defaultPickupStopId: "s2",
    defaultDropoffStopId: "s2",
    defaultRouteId: "r1",
    notes: "Cần hỗ trợ lên xuống xe",
  },
  {
    id: "st4",
    code: "HS004",
    name: "Phạm Thu Hà",
    grade: "6D",
    school: "THCS Chu Văn An",
    defaultPickupStopId: "s2",
    defaultDropoffStopId: "s2",
    defaultRouteId: "r1",
  },
  {
    id: "st5",
    code: "HS005",
    name: "Vũ Đức Minh",
    grade: "9A",
    school: "THCS Chu Văn An",
    defaultPickupStopId: "s3",
    defaultDropoffStopId: "s3",
    defaultRouteId: "r2",
  },
]

// Mock incidents
export const mockIncidents: Incident[] = [
  {
    id: "i1",
    routeId: "r1",
    vehicleId: "v1",
    driverId: "d1",
    type: "delay",
    severity: "minor",
    status: "in-progress",
    description: "Kẹt xe tại ngã tư Ô Chợ Dừa, dự kiến trễ 10 phút",
    location: { lat: 21.0245, lng: 105.8412 },
    reportedAt: new Date(Date.now() - 15 * 60000).toISOString(),
    reportedBy: "d1",
    assignedTo: "dispatcher1",
    timeline: [
      {
        timestamp: new Date(Date.now() - 15 * 60000).toISOString(),
        action: "Sự cố được báo cáo",
        user: "d1",
      },
      {
        timestamp: new Date(Date.now() - 10 * 60000).toISOString(),
        action: "Đã gán cho điều phối viên",
        user: "system",
      },
    ],
  },
  {
    id: "i2",
    routeId: "r2",
    vehicleId: "v2",
    driverId: "d2",
    type: "route-deviation",
    severity: "major",
    status: "open",
    description: "Phải đi đường vòng do đường chính đang sửa chữa",
    location: { lat: 21.0015, lng: 105.8312 },
    reportedAt: new Date(Date.now() - 5 * 60000).toISOString(),
    reportedBy: "d2",
    timeline: [
      {
        timestamp: new Date(Date.now() - 5 * 60000).toISOString(),
        action: "Sự cố được báo cáo",
        user: "d2",
      },
    ],
  },
]

// Mock dashboard KPIs
export const mockDashboardKPI: DashboardKPI = {
  activeRoutes: 12,
  activeVehicles: 10,
  totalVehicles: 15,
  studentsPickedUp: 245,
  totalStudents: 320,
  openIncidents: 2,
  onTimePerformance: 94.5,
}
